using System.Collections;
using System.Collections.Generic;
using UnityEngine;
public class ACOTester : MonoBehaviour
{
    // The ACO Controller.
    ACOCON MyACOCON = new ACOCON();
    // Array of possible waypoints.
    List<GameObject> Waypoints = new List<GameObject>();
    // Connections between nodes.
    private List<Connection> Connections = new List<Connection>();
    // The route generated by the ACO algorith.
    private List<Connection> MyRoute = new List<Connection>();
    // Debug line offset.
    private Vector3 OffSet = new Vector3(0, 0.5f, 0);
    private int count = 0;
    private int stop = 0;
    private bool reverse = false;
    public float speed = 5;
    // The Start node for any created route.
    public GameObject StartNode;
    // The max length of a path created by the ACO.
    public int MaxPathLength;
    // Start is called before the first frame update
    void Start()
    {
        // Find all the waypoints in the level.
        GameObject[] GameObjectsWithWaypointTag;
        GameObjectsWithWaypointTag = GameObject.FindGameObjectsWithTag("Waypoint");
        foreach (GameObject waypoint in GameObjectsWithWaypointTag)
        {
            WaypointCON tmpWaypointCon = waypoint.GetComponent<WaypointCON>();
            if (tmpWaypointCon)
            {
                if (tmpWaypointCon.WaypointType == WaypointCON.waypointPropsList.Goal)
                {
                    // We are creating a waypoint map of only the goal nodes. We want out ACO ato create the shortest path between the goal nodes.
                    Waypoints.Add(waypoint);
                }
            }
        }
        // Go through the waypoints and create connections.
        foreach (GameObject waypoint in Waypoints)
        {
            WaypointCON tmpWaypointCon = waypoint.GetComponent<WaypointCON>();
            // Loop through a waypoints connections.
            foreach (GameObject WaypointConNode in tmpWaypointCon.Connections)
            {
                Connection aConnection = new Connection();
                aConnection.SetConnection(waypoint, WaypointConNode, MyACOCON.GetDefaultPheromone());
                Connections.Add(aConnection);
            }
        }
        MyRoute = MyACOCON.ACO(150, 50, Waypoints.ToArray(), Connections, StartNode, MaxPathLength);
    }
    void OnDrawGizmos()
    {
        // Draw path.
        if (MyRoute.Count > 0)
        {
            foreach (Connection aConnection in MyRoute)
            {
                Gizmos.color = Color.yellow;
                Gizmos.DrawLine((aConnection.GetFromNode().transform.position + OffSet),
                (aConnection.GetToNode().transform.position + OffSet));
            }
        }
    }
    // Update is called once per frame
    void Update()
    {
        // To prevent index out of bound
        if (count < MyRoute.Count)
        {
            if (!reverse)
            {
                // To detect if cube has reached its destination
                if (transform.position != MyRoute[count].GetToNode().transform.position)
                {
                    //move forward to a position
                    transform.position = Vector3.MoveTowards(transform.position, MyRoute[count].GetToNode().transform.position, Time.deltaTime * speed);
                }
                else
                {
                    // if cube us reached to its destination then increment count by 1
                    count++;
                }
            }
            else
            {
                //  To detect if cube reached its destination
                if (transform.position != MyRoute[count].GetFromNode().transform.position)
                {
                    //move forward to a position
                    transform.position = Vector3.MoveTowards(transform.position, MyRoute[count].GetFromNode().transform.position, Time.deltaTime * speed);
                }
                else
                {
                    // if cube us reached to its destination then increment count by 1
                    count++;
                }
            }
        }

        // For Changing direction
        if (count == MyRoute.Count)
        {
            if (stop < 1)
            {
                stop += 1;
                count = 0;
            }


            //reverse both variable and the list
            reverse = !reverse;
            MyRoute.Reverse();
        }
    }
}

